Repository BoldGrid/w3-total-cache, pull requests merged in 2024-09, with the labels that each got.

#950 GPS Fix - Plugin
  PageSpeed_Api.php
  PageSpeed_Instructions.php
  inc/options/general.php
Labels: enhancement

#956 Statistics Widget Warning Fix
  PgCache_Plugin_Admin.php
Labels: bug

#955 License Status Fix
  Generic_WidgetAccount_View.php
Labels: bug

#952 Fragment Cache link issue
  inc/options/common/top_nav_bar.php
Labels: bug

#953 DB Cache Disk Notice
  inc/options/general.php
  pub/css/options.css
  pub/js/options.js
Labels: enhancement

#865 Object Cache - actualize
  ConfigKeys.php
  Extension_FragmentCache_WpObjectCache.php
  ObjectCache_Plugin.php
  ObjectCache_WpObjectCache.php
  ObjectCache_WpObjectCache_Regular.php
  inc/options/general.php
  pub/css/options.css
  pub/js/options.js
  qa/plugins/objectcache/basic.php
  qa/tests/objectcache/basic.js
  wp-content/object-cache.php
Labels: enhancement, Scope: Medium, php

#958 Update Nginx examples
  ini/nginx-network-sample-config.conf
  ini/nginx-standalone-sample-config.conf
Labels: documentation

#882 Always Cached
  Cache_Apc.php
  Cache_Apcu.php
  Cache_Base.php
  Cache_Eaccelerator.php
  Cache_File.php
  Cache_File_Cleaner.php
  Cache_File_Cleaner_Generic.php
  Cache_File_Cleaner_Generic_HardDelete.php
  Cache_File_Generic.php
  Cache_Memcache.php
  Cache_Memcached.php
  Cache_Redis.php
  Cache_Wincache.php
  Cache_Xcache.php
  Cli.php
  Extension_AlwaysCached_AdminActions.php
  Extension_AlwaysCached_Environment.php
  Extension_AlwaysCached_Page.php
  Extension_AlwaysCached_Page_Queue_View.php
  Extension_AlwaysCached_Page_View.js
  Extension_AlwaysCached_Page_View.php
  Extension_AlwaysCached_Page_View_BoxCron.php
  Extension_AlwaysCached_Page_View_BoxFlushAll.php
  Extension_AlwaysCached_Page_View_BoxQueue.php
  Extension_AlwaysCached_Page_View_Exclusions.php
  Extension_AlwaysCached_Plugin.php
  Extension_AlwaysCached_Plugin_Admin.php
  Extension_AlwaysCached_Queue.php
  Extension_AlwaysCached_Worker.php
  Extensions_Page.php
  Extensions_Plugin_Admin.php
  FeatureShowcase_Plugin_Admin.php
  Generic_Page_Install.php
  Generic_Plugin.php
  PgCache_ContentGrabber.php
  PgCache_Environment.php
  PgCache_Flush.php
  Root_Environment.php
  Util_PageUrls.php
  Util_Ui.php
  inc/options/pgcache.php
  pub/css/options.css
Labels: enhancement, Scope: Medium, php, Feature
