Repository BoldGrid/w3-total-cache, pull requests merged in 2024-12, with the labels that each got.

#1004 Fixed undefined variable
  ObjectCache_WpObjectCache_Regular.php
Labels: bug

#1009 Object Cache fixes
  ConfigKeys.php
  DbCache_WpdbInjection_QueryCaching.php
  Extension_FragmentCache_WpObjectCache.php
  Generic_Faq.php
  Generic_Plugin_Admin.php
  ObjectCache_WpObjectCache_Regular.php
  SetupGuide_Plugin_Admin.php
  Util_Admin.php
  composer.lock
  inc/options/cdn.php
  inc/options/general.php
  inc/options/install.php
  inc/options/pgcache.php
  languages/w3-total-cache.pot
  pub/js/setup-guide.js
  qa/env/100-generate-envs
  readme.txt
  w3-total-cache-api.php
  w3-total-cache.php
  yarn.lock
Labels: bug, enhancement, C: Setup Guide, Scope: Low

#1010 Add user compatibility checks
  BrowserCache_Plugin.php
  Extension_ImageService_Plugin_Admin.php
  Extensions_Plugin_Admin.php
  Generic_Plugin_Admin.php
  Generic_Plugin_AdminNotices.php
  Generic_WidgetStats.php
  ObjectCache_WpObjectCache_Regular.php
  PgCache_ContentGrabber.php
  Util_Debug.php
  Util_File.php
  inc/options/common/footer.php
  inc/options/common/top_nav_bar.php
Labels: bug, Scope: Low

#1005 Object Cache Drop In Feature Enable Check
  wp-content/object-cache.php
Labels: bug
