Repository BoldGrid/w3-total-cache, pull requests merged in 2025-01, with the labels that each got.

#1032 Fix check for advanced-cache.php file. Fixes #1025
  Generic_Environment.php
Labels: bug

#1036 Browser Cache Security Header Fix
  BrowserCache_Environment.php
  BrowserCache_Environment_Nginx.php
Labels: bug

#1035 Browser Cache CSS/JS and Other/Media Cache Policy Immutable
  BrowserCache_Environment.php
  BrowserCache_Environment_LiteSpeed.php
  BrowserCache_Environment_Nginx.php
  BrowserCache_Plugin.php
  Minify_Environment.php
  inc/options/browsercache.php
Labels: enhancement

#1039 Added descriptions for registered CLI aliases.
  Cli.php
Labels: enhancement, Scope: Low

#1041 Fix survey and GA JS
  Generic_Plugin_Admin.php
  pub/js/exit-survey.js
Labels: bug

#1045 Fix GA issues
  Generic_Plugin_Admin.php
  pub/js/options.js
Labels: bug

#1047 Nginx Page Cache - Disk Enhanced Fix
  PgCache_Environment.php
Labels: bug
