Repository BoldGrid/w3-total-cache, pull requests merged in 2025-02, with the labels that each got.

#1046 License Verify/Apply Update
  Licensing_Core.php
  Licensing_Plugin_Admin.php
  Root_AdminActivation.php
  Root_Environment.php
  inc/options/general.php
  pub/js/options.js
Labels: enhancement

#1052 Fix fatal CLI Always Cached error
  Cli.php
  Extension_AlwaysCached_Worker.php
Labels: bug

#1054 Add settings to enable objectcache and dbcache for WP-CLI
  ConfigKeys.php
  DbCache_WpdbInjection_QueryCaching.php
  ObjectCache_WpObjectCache_Regular.php
  Util_File.php
  inc/options/dbcache.php
  inc/options/objectcache.php
Labels: enhancement

#1055 Added email field to exit survey
  Generic_Plugin_Survey.php
  inc/lightbox/exit_survey.php
Labels: enhancement

#1056 Fix WP-CLI Object Cache
  ObjectCache_Environment.php
  wp-content/object-cache.php
Labels: bug

#1058 Add phpunit tests
  Root_Environment.php
  tests/admin/class-w3tc-admin-root-environment.php
  tests/admin/class-w3tc-admin-util-environment.php
Labels: bug, enhancement

#1057 Object Cache Disk Modal For Risk Acceptance
  Minify_GeneralPage_View_ShowHelp.js
  ObjectCache_DiskPopup.js
  ObjectCache_DiskPopup_View.php
  ObjectCache_Plugin_Admin.php
  pub/css/lightbox.css
  pub/css/popup.css
Labels: enhancement

#1064 Exit Survey data delete on skip
  Generic_Plugin_Survey.php
  inc/lightbox/exit_survey.php
  pub/js/exit-survey.js
Labels: enhancement
